AllCops:
  Exclude:
    - bundle/**/*
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 175

# those metrics should be disabled
Metrics/AbcSize:
  Max: 93

Metrics/BlockLength:
  Max: 188

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 285

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 70

Metrics/ParameterLists:
  Max: 18
  MaxOptionalParameters: 5

Metrics/PerceivedComplexity:
  Max: 26

# We use `dc` as a parameter in many methods
Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

